\name : Foundation5/github pages/Jykill starter
brand : Dice Media Group
description : Landing page for Dice Media Group
keyword : 
url : https://dice-media-group.github.io/
email : carl@dicemediagroup.com
twitter : DaigoFuji
github : DaigoFuji
author : Dice Media Group
year : 2018
markdown : kramdown
exclude :
  - node_modules
